DjangoDemo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

from user.urls import router as user_router
from nestedrelations.urls import router as nestedrelations_router
from sortnpage.urls import router as sortnpage_router
from grouppermissions.urls import router as grouppermissions_router
from countrydropdown.urls import router as countrydropdown_router
from bulkupdate.urls import router as bulkupdate_router
from phonenumbers.urls import router as phonenumbers_router

router = routers.DefaultRouter()
router.registry.extend(user_router.registry)
router.registry.extend(nestedrelations_router.registry)
router.registry.extend(sortnpage_router.registry)
router.registry.extend(grouppermissions_router.registry)
router.registry.extend(countrydropdown_router.registry)
router.registry.extend(bulkupdate_router.registry)
router.registry.extend(phonenumbers_router.registry)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('nestedrelations/',include('nestedrelations.urls')),
    path('sortnpage/',include('sortnpage.urls')),
    path('grouppermissions/',include('grouppermissions.urls')),
    path('countrydropdown/',include('countrydropdown.urls')),
    path('bulkupdate/',include('bulkupdate.urls')),
    path('phonenumbers/',include('phonenumbers.urls')),
]

sortnpage/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .viewsets import PaginationDemoViewSet, IncidentViewSet, DateRangeAndDurationViewSet

router = routers.SimpleRouter()
router.register(r'pagination-demos', PaginationDemoViewSet)
router.register(r'incidents', IncidentViewSet)
router.register(r'date-range-and-durations', DateRangeAndDurationViewSet)

urlpatterns = [
    path('pagination-demos/', views.PaginationDemoList.as_view(), name='PaginationDemoList'),
    path('pagination-demos-datatables/', views.PaginationDemoListDatatables.as_view(), name='PaginationDemoListDatatables'),
    path('pagination-demos-data/', views.PaginationDemoListData.as_view(), name='PaginationDemoListData'),
    path('pagination-demo/<pk>', views.PaginationDemoDetail.as_view(), name='PaginationDemoDetail'),
    path('incident-create/', views.IncidentCreateView.as_view(), name='IncidentCreate'),
    path('date-range-and-durations-create/', views.DateRangeAndDurationCreateView.as_view(), name='DateRangeAndDurationCreate'),
]

user/urls.py
from rest_framework import routers

from .viewsets import UserViewSet

router = routers.SimpleRouter()
router.register(r'users', UserViewSet)

sortnpage/models.py
from django.db import models
import uuid


# Create your models here.
class PaginationDemo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=127, null=False)
    amount = models.PositiveIntegerField(null=False)
    uuId = models.UUIDField(default=uuid.uuid4, editable=False, db_index=True)
    createdAt = models.DateField(auto_now_add=True)


class Incident(models.Model):
    number = models.CharField(max_length=127, null=False)  # A123-00, A123-01
    iteration = models.PositiveIntegerField(null=False, editable=False)  # 0
    date = models.DateField()

    def save(self, *args, **kwargs):
        if self.pk is None:  # New object is being created
            self.iteration = int(self.number.split("-")[-1])
        super().save(*args, **kwargs)


class DateRangeAndDuration(models.Model):
    start_date = models.DateField(null=False)
    end_date = models.DateField(null=False)
    duration_days = models.PositiveIntegerField(null=False)

sortnpage/forms.py
import datetime
from django import forms
from django.db.models import fields
from tempus_dominus.widgets import DatePicker

from .models import Incident, DateRangeAndDuration


# class CustomDateField(forms.DateField):
#     def to_python(self, value):
#         print(value)
#         formatted_value = datetime.datetime.strptime(value, "%d-%m-%Y").strftime(
#             "%Y-%m-%d"
#         )
#         return super().to_python(formatted_value)


class IncidentForm(forms.ModelForm):
    # date = CustomDateField(widget=DatePicker(options={"format": "DD-MM-YYYY"}))

    class Meta:
        model = Incident
        fields = "__all__"
        widgets = {"date": DatePicker(options={"format": "DD-MM-YYYY"})}


class DateRangeAndDurationForm(forms.ModelForm):
    class Meta:
        model = DateRangeAndDuration
        fields = "__all__"
        widgets = {
            "start_date": DatePicker(options={"format": "DD-MM-YYYY"}),
            "end_date": DatePicker(options={"format": "DD-MM-YYYY"}),
        }

sortnpage/views.py
from datetime import datetime, timedelta
from django.views.generic import ListView, DetailView, View, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.core.paginator import Paginator
from django.http.response import JsonResponse

from .models import PaginationDemo, Incident, DateRangeAndDuration
from .serializers import PaginationDemoSerializer
from .filters import PaginationDemoFilter
from .forms import IncidentForm, DateRangeAndDurationForm


class PaginationDemoList(LoginRequiredMixin, ListView):
    model = PaginationDemo
    # login_url = '/api-auth/login/'
    paginate_by = 10
    # ordering = ['name']

    def get_ordering(self):
        ordering = self.request.GET.get("ordering", "amount")

        # validate ordering
        if ordering not in (
            "name",
            "amount",
            "-name",
            "-amount",
        ):
            ordering = "amount"

        return ordering


class PaginationDemoDetail(LoginRequiredMixin, DetailView):
    model = PaginationDemo
    # login_url = '/api-auth/login/'

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        obj = PaginationDemo.objects.get(uuId=pk)
        return obj


class PaginationDemoListDatatables(View):

    def get_context_data(self):
        today = datetime.today()
        last_7_day = today - timedelta(days=7)
        last_8_day = last_7_day - timedelta(days=1)
        context = {
            "today": today.strftime("%Y-%m-%d"),
            "last_7_day": last_7_day.strftime("%Y-%m-%d"),
            "last_8_day": last_8_day.strftime("%Y-%m-%d"),
        }
        return context

    def get(self, request):
        context = self.get_context_data()
        return render(
            request, "sortnpage/paginationdemo_list_datatables.html", context=context
        )


class PaginationDemoListData(View):
    def get(self, request):
        # print(request.GET)

        # Pagination limit and offset
        try:
            start = int(request.GET.get("start", 0))
        except ValueError:
            start = 0
        try:
            length = int(request.GET.get("length", 10))
        except ValueError:
            length = 10

        columns = ["id", "name", "amount", "createdAt"]
        ordering = "name"

        # Order Column
        try:
            order_col = int(request.GET.get("order[0][column]", 1))
        except ValueError:
            order_col = 1
        if order_col:
            try:
                ordering = columns[order_col]
            except KeyError:
                pass

        # Order Direction
        order_dir = request.GET.get("order[0][dir]")
        if order_dir and order_dir == "desc":
            ordering = "-" + ordering

        allObjects = PaginationDemo.objects.all().order_by(ordering)
        filtered_objects = PaginationDemoFilter(request.GET, queryset=allObjects).qs

        # Add paginator
        # paginator = Paginator(allObjects, length)
        paginator = Paginator(filtered_objects, length)
        page = (start // length) + 1
        pageObjects_list = paginator.get_page(page)

        return JsonResponse(
            {
                # "recordsTotal": paginator.count,
                "recordsTotal": allObjects.count(),
                "recordsFiltered": paginator.count,
                "data": PaginationDemoSerializer(pageObjects_list, many=True).data,
            }
        )


class IncidentCreateView(CreateView):
    model = Incident
    form_class = IncidentForm
    success_url = "/incidents/"


class DateRangeAndDurationCreateView(CreateView):
    model = DateRangeAndDuration
    form_class = DateRangeAndDurationForm
    success_url = "/date-range-and-durations/"

sortnpage/templates/sortnpage/daterangeandduration_form.html
{% extends "base.html" %}
{% block title %}Date Range and Duration Create{% endblock %}
{% block head %}
{# Include Bootstrap 4 #}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
{{ form.media }}
{% endblock head %}
{% block header_text %}Date Range and Duration Create{% endblock %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-primary">Save</button>
</form>
{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(function () {
    $("#id_start_date").on('change.datetimepicker', e => {
      const start_date = e.date;
      const end_date = $('#id_end_date').datetimepicker('viewDate');
      const duration = moment.duration(end_date.diff(start_date));
      $("#id_duration_days").val(duration.asDays());
    });
    $("#id_end_date").on('change.datetimepicker', e => {
      const start_date = $('#id_start_date').datetimepicker('viewDate');
      const end_date = e.date;
      const duration = moment.duration(end_date.diff(start_date));
      $("#id_duration_days").val(duration.asDays());
    });
  });
</script>
{% endblock scripts %}

sortnpage/templates/sortnpage/incident_form.html
{% extends "base.html" %}
{% block title %}Incident Create{% endblock %}
{% block head %}
{# Include Bootstrap 4 and jQuery #}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
{{ form.media }}
{% endblock head %}
{% block header_text %}Incident Create{% endblock %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-primary">Save</button>
</form>
{% endblock content %}

sortnpage/templates/sortnpage/paginationdemo_detail.html
<h1>Name: {{object.name}}</h1>
<p>Amount: {{object.amount}}</p>
<p>ID: {{object.id}}</p>

sortnpage/templates/sortnpage/paginationdemo_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PaginationDemos List</title>
    <style>
        table,
        th,
        td {
            border: 1px solid black;
            border-collapse: collapse;
        }
    </style>
</head>

<body>
    <h2>PaginationDemos</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>Url</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in page_obj %}
            <tr>
                <td>{{ obj.name }}</td>
                <td>{{ obj.amount }}</td>
                <td><a href="{% url 'PaginationDemoDetail' pk=obj.id %}">{{ obj.id }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a class="paginiation-link" href="?page=1">&laquo; first</a>
            <a class="paginiation-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a class="paginiation-link" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="paginiation-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    <!-- Sort -->
    <div>
        <form>
            <select name="ordering">
                <option value="name">Name Asc</option>
                <option value="-name">Name Desc</option>
                <option value="amount">Amount Asc</option>
                <option value="-amount">Amount Desc</option>
            </select>
            <button class="btn btn-primary" type="submit">Sort</button>
        </form>
    </div>
    <script>
        document.querySelectorAll('.paginiation-link').forEach(elem => {
            elem.addEventListener('click', (e) => {
                e.preventDefault();
                const [key, val] = elem.getAttribute('href').substr(1).split('=')
                const url = new URL(location);
                url.searchParams.set(key, val);
                location.href = url.toString();
            })
        })
    </script>
</body>

</html>

sortnpage/templates/sortnpage/paginationdemo_list_datatables.html
{% extends "base.html" %}
{% block title %}PaginationDemos List{% endblock %}
{% block head %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.24/datatables.min.css" />
{% endblock head %}

{% block header_text %}PaginationDemos{% endblock %}
{% block content %}
<form class="row my-4">
    <div class="col-md-3">
        <label for="id_filter_name" class="form-label">Name</label>
        <input class="form-control" id="id_filter_name" name="name" value="{{ request.GET.name }}" />
    </div>
    <div class="col-md-3">
        <label for="id_filter_amount" class="form-label">Amount</label>
        <input type="number" class="form-control" id="id_filter_amount" name="amount"
            value="{{ request.GET.amount }}" />
    </div>
    <div class="col-md-3">
        <label for="id_filter_amount" class="form-label">Date Range</label>
        <input type="text" class="form-control" id="id_daterange" value="" />
        <input hidden type="text" class="form-control" id="id_createdAt_gte" name="createdAt_gte"
            value="{{ request.GET.createdAt_gte }}" />
        <input hidden type="text" class="form-control" id="id_createdAt_lte" name="createdAt_lte"
            value="{{ request.GET.createdAt_lte }}" />
    </div>
    <div class="col-1 d-grid align-items-end mx-auto">
        <button type="submit" class="btn btn-primary">Filter</button>
    </div>
    <div class="col-1 d-grid align-items-end mx-auto">
        <a href="/sortnpage/pagination-demos-datatables/">
            <button type="button" class="btn btn-primary">Reset</button>
        </a>
    </div>
</form>
<div class="d-flex justify-content-evenly">
    <a href="{% url 'PaginationDemoListDatatables' %}?createdAt_lte={{ today }}&createdAt_gte={{ last_7_day }}">
        Created in last 7 days
    </a>
    <a href="{% url 'PaginationDemoListDatatables' %}?createdAt_lte={{ last_8_day }}">Created earlier</a>
</div>
<hr />
<table id="datatable" class="table table-hover table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Amount</th>
            <th>Created At</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>id</td>
            <td>name</td>
            <td>amount</td>
            <td>craetedAt</td>
        </tr>
    </tbody>
</table>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.24/datatables.min.js"></script>
<!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script> -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<script>
    // Initialize datatable
    $(document).ready(function () {
        $('#datatable').DataTable({
            processing: true,
            serverSide: true,
            ajax: "/sortnpage/pagination-demos-data/" + window.location.search,
            columns: [
                { data: 'id', orderable: false },
                { data: 'name', className: 'name' },
                { data: 'amount', className: 'amount' },
                { data: 'createdAt', render: (val) => new Date(val).toLocaleDateString('en-AU') },
            ],
            order: [[1, "asc"]],
            createdRow: function (row, data, dataIndex) {
                // console.log(row, data, dataIndex);
                if (data.amount === 0) $(row).children('.name').addClass('text-danger')
                if (data.amount > 0) $(row).children('.amount').addClass('text-success')
            },
        });
    });
    // Initialize date range picker
    const start = "{{ request.GET.createdAt_gte }}";
    const end = "{{ request.GET.createdAt_lte }}";
    const startDate = start ? moment(start).format("DD/MM/YYYY") : undefined;
    const endDate = end ? moment(end).format("DD/MM/YYYY") : undefined;
    if (startDate && endDate) $('#id_daterange').val(startDate + " - " + endDate);
    $('#id_daterange').daterangepicker({
        autoUpdateInput: false,
        locale: {
            format: "DD/MM/YYYY",
            separator: " - ",
            cancelLabel: 'Clear'
        }
    });
    $('#id_daterange').on('apply.daterangepicker', function (ev, picker) {
        $(this).val(picker.startDate.format('DD/MM/YYYY') + ' - ' + picker.endDate.format('DD/MM/YYYY'));
        $("#id_createdAt_gte").val(picker.startDate.format('YYYY-MM-DD'));
        $("#id_createdAt_lte").val(picker.endDate.format('YYYY-MM-DD'));
    });
    $('#id_daterange').on('cancel.daterangepicker', function (ev, picker) {
        $(this).val('');
        $("#id_createdAt_gte").val('');
        $("#id_createdAt_lte").val('');
    });
</script>
{% endblock %}